
//reference: https://www.geeksforgeeks.org/html/how-to-generate-pdf-file-using-jspdf-library/

class PDFService {
    constructor() {
    }
    async createPDF(content) {
    
    const { jsPDF } = window.jspdf; //get this from the imported script in index.html
    const doc = new jsPDF();
    doc.setFontSize(18); 
    doc.text("My Weekly Workout Plan", 14, 20); //set title of the pdf
    
    doc.setFontSize(11);
    doc.text("Generated by AI Trainer", 14, 28);
    const tableRows = content.map(day => { //use content to loop through the days, and list down all the contents
        const exerciseList = day.exercises.map(ex => 
            `• ${ex.name}: ${ex.sets} sets x ${ex.reps}`
        ).join("\n");

        return [
            day.day,       
            day.focus,    
            exerciseList  
        ];
    });

    doc.autoTable({ //autotable plugin to create table, imported in index.html
        head: [['Day', 'Target Focus', 'Exercises']],
        body: tableRows,
        startY: 35, 
        

        theme: 'grid', 
        headStyles: { fillColor: [41, 128, 185], textColor: 255, fontStyle: 'bold' }, 
        styles: { fontSize: 10, cellPadding: 3, valign: 'middle' },

        columnStyles: {
            0: { cellWidth: 25, fontStyle: 'bold' },
            1: { cellWidth: 40 }, 
            2: { cellWidth: 'auto' } 
        },
        
     
        pageBreak: 'auto'
    });

    doc.save('weekly_workout_schedule.pdf'); //save the pdf as weekly_workout_schedule.pdf
}
}
export default PDFService;